### ISSUE TITLE
1.12 Can't start new server. 

### ISSUE THREAD

**Issue by whatthedrunk** [ProfessorProspector/Traverse#2]
Getting insane console spam repeating this over and over. 

[22:25:03] [Server thread/INFO]: [STDERR]: 	at prospector.traverse.world.TraverseWorldVersion.writeVersionFile(TraverseWorldVersion.java:56)
[22:25:03] [Server thread/INFO]: [STDERR]: 	at prospector.traverse.world.TraverseWorldVersion.reloadVersionFile(TraverseWorldVersion.java:33)

**Comment by ProfessorProspector** [comment]
On 1.1.6? Huh it works fine for me in dev.

**Comment by ProfessorProspector** [comment]
Fixed in 1.1.7
